### PR TITLE
Schema for the JPBAKERYFT bankend project

### PR DESCRIPTION
**Pull request by samueleffiongjacob**
user model

user model half screenshot see code for details.
payment

user payment half screenshot see code for details.
order moldels

user order half screenshot see code for details.

please kindly review and give me feedback

### CODE REVIEW

**Review by Learnuel1 — COMMENTED** [review]
I don't see the need for the createAt and updatedAt fields since the mongoose does this through the timestamps:true function.

**Comment by xarmzon** [comment]
@samueleffiongjacob  compare line 30-32 of  server/src/models/order.model.js to line 7 and 8 of  server/src/models/payment.model.js


The line 7-8 needs to be like line 30-32 with reference to necessary model

**Comment by xarmzon** [comment]
Also @samueleffiongjacob  you don't need to add updateAt and createdAt... The mongoose timestamp: true will do that. 


Remove them from the schemas

**Comment by xarmzon** [comment]
@samueleffiongjacob  ref key in the schema inside server/src/models/payment.model.js should have required: true

**Comment by xarmzon** [comment]
Also, watch out for the typos in your code and commit messages

**Review by xarmzon — CHANGES_REQUESTED** [review]
Follow the messages sent on the changes to make to the code. Thank you

**Comment by samueleffiongjacob** [comment]
> I don't see the need for the createAt and updatedAt fields since the mongoose does this through the timestamps:true function.

update and created date remove from all pages

corrected sir

**Comment by samueleffiongjacob** [comment]
> @samueleffiongjacob compare line 30-32 of server/src/models/order.model.js to line 7 and 8 of server/src/models/payment.model.js
> 
> The line 7-8 needs to be like line 30-32 with reference to necessary model

order id with corrections on payment models

corrected

**Comment by samueleffiongjacob** [comment]
> Also @samueleffiongjacob you don't need to add updateAt and createdAt... The mongoose timestamp: true will do that.
> 
> Remove them from the schemas

update and created date remove from all pages


corrected

**Comment by samueleffiongjacob** [comment]
> @samueleffiongjacob ref key in the schema inside server/src/models/payment.model.js should have required: true

ref with corrections on payment models

corrected

**Comment by samueleffiongjacob** [comment]
> Also, watch out for the typos in your code and commit messages

aright sir typo notice was (require ---> required)

**Review by xarmzon — CHANGES_REQUESTED** [review]
Line 9:  server/src/models/order.model.js

cakename should be cakeName

**Comment by samueleffiongjacob** [comment]
> Line 9: server/src/models/order.model.js
> 
> cakename should be cakeName

cakeName

cakename -----> cakeName

**Review by EAZYLINK — DISMISSED** [review]
unique for orderId was repeated twice, remove one

**Review by xarmzon — CHANGES_REQUESTED** [review]
@samueleffiongjacob  Remove line 13 in server/src/models/order.model.js

**Review by xarmzon — CHANGES_REQUESTED** [review]
@samueleffiongjacob Remove line 12 in  server/src/models/payment.model.js

**Review by Learnuel1 — APPROVED** [review]
Ok

**Comment by samueleffiongjacob** [comment]
> unique for orderId was repeated twice, remove one

LINE 12 REMOVED


it is not there it may be git is showing u what l change or deleted

**Comment by samueleffiongjacob** [comment]
> @samueleffiongjacob Remove line 12 in server/src/models/payment.model.js

LINE 12 REMOVED

LINE 12 DELETED

**Comment by samueleffiongjacob** [comment]
> @samueleffiongjacob Remove line 13 in server/src/models/order.model.js

line 13 remove

line 13 removed

**Review by Learnuel1 — COMMENTED** [review]
1. The orderSchema is not reference any product how do we know which cake was ordered,
2. The status field is default the buyer which is not contained in the enum, is this okay?

**Comment by xarmzon** [comment]
> 1. The orderSchema is not reference any product how do we know which cake was ordered,
> 2. The status field is default the buyer which is not contained in the enum, is this okay?

Nothing like product here.. Buyers are to send their custom cake requests not the one posted by admin

**Review by xarmzon — APPROVED** [review]

**Pull request merged**
